### ISSUE TITLE
No Registration screen

### ISSUE THREAD

**Issue by MuhammadZain7** [shravansuthar210/face-recognition-attendance-android-app#1]
How can i register in thi app

**Comment by shravansuthar210** [comment]
yes , because student and teacher can be register by admin.
admin can remove or add student and teacher. 
you can register admin follow this step
step 1 firebase json past in application
step 2 go to firebase console and add admin emaill and password
step 3 boom

**Comment by Pr0fe5s0r** [comment]
can you say about the structure of the firebase so that we can create it? There is no source for it!!

**Comment by shravansuthar210** [comment]
my firebase structure are so bad and till date i  don't updated. 


{
  "Attandance" : {
    "BSCIT" : {
      "FY_1" : {
        "a" : [ 

        ]
      }
    }
  },
  "Attandancedetail" : {
    "BSCIT" : {
      "FY_1" : {
        "a" : {
          
        }
      }
    }
  },
  "Message" : {
    "-M3HCloCoP9YHd63v_W5" : {
      "fro" : "BSCITFY",
      "message" : "hejshsjsjz",
      "sender" : "shravan kumar suthar",
      "subject" : "jsjsjsj",
      "time" : "20:32 25.03.2020"
    }
  },
  "Profile" : {
    "3Sfk9Jc5xccd86pDsAvF2UUImQy1" : {
      "addresss" : "hsjsjsbzbzbznzn",
      "birthofdate" : "11/13/3000",
      "course" : "BSCIT",
      "division" : "a",
      "email" : "hitesh@gmail.com",
      "fullname" : "hitesh suthar",
      "numbers" : "1234567890",
      "password" : "1234567890",
      "rollnumber" : "2",
      "uid" : "3Sfk9Jc5xccd86pDsAvF2UUImQy1",
      "usertype" : "Student",
      "year" : "FY"
    },
    "7msk9qnSpIVpA4WlmEkJ1pAtjTI2" : {
      "addresss" : "nallasopara west",
      "birthofdate" : "11/13/3000",
      "courece" : "BSCIT",
      "degree" : "mca",
      "email" : "suthar210@gmail.com",
      "fullname" : "shravan kumar suthar",
      "numbers" : "1234567890",
      "password" : "qwerty",
      "uid" : "7msk9qnSpIVpA4WlmEkJ1pAtjTI2",
      "usertype" : "Teacher"
    },
    "WkHk4CTzaUXCSnG5xrI9spGEZAH3" : {
      "addresss" : "nallasopara west",
      "birthofdate" : "11/13/3000",
      "course" : "BSCIT",
      "division" : "a",
      "email" : "shravansuthar@gmail.com",
      "fullname" : "shravan kumar suthar",
      "numbers" : "1234567890",
      "password" : "1234567890",
      "rollnumber" : "1",
      "uid" : "WkHk4CTzaUXCSnG5xrI9spGEZAH3",
      "usertype" : "Student",
      "year" : "FY"
    }
  },
  "Student" : {
    "BSCIT" : {
      "FY" : {
        "a" : [ {
          "address" : "nallasopara west",
          "brithofDate" : "11/13/3000",
          "course" : "BSCITFY",
          "division" : "a",
          "email" : "shravansuthar@gmail.com",
          "fullName" : "shravan kumar suthar",
          "number" : "1234567890",
          "rollNumber" : "1",
          "uid" : "WkHk4CTzaUXCSnG5xrI9spGEZAH3"
        }, {
          "address" : "Harji,Jalore(Raj)",
          "brithofDate" : "11/13/3000",
          "course" : "BSCITFY",
          "division" : "a",
          "email" : "hitesh@gmail.com",
          "fullName" : "hitesh suthar",
          "number" : "1234567890",
          "rollNumber" : "2",
          "uid" : "3Sfk9Jc5xccd86pDsAvF2UUImQy1"
        } ]
      }
    }
  },
  "Teacher" : {
    "7msk9qnSpIVpA4WlmEkJ1pAtjTI2" : {
      "addresss" : "nallasopara west",
      "birthofdate" : "11/13/3000",
      "courese" : "BSCIT",
      "degree" : "mca",
      "email" : "suthar210@gmail.com",
      "fullname" : "shravan kumar suthar",
      "numbers" : "1234567890",
      "uid" : "7msk9qnSpIVpA4WlmEkJ1pAtjTI2"
    }
  }
}

**Comment by shravansuthar210** [comment]
my firebase structure are so bad and till date i don't  updated. so manage
[attendance-904ed-export.zip](https://github.com/shravansuthar210/face-recognition-attendance-android-app/files/8309373/attendance-904ed-export.zip)

**Comment by Pr0fe5s0r** [comment]
thank you @shravansuthar210. By the way nice project!
